CREATE DATABASE Pizzariaproject;

USE Pizzariaproject;

CREATE TABLE CATEGORIAS(
	ID_CAT INT NOT NULL,
	NM_CAT VARCHAR(255) NOT NULL,
	CONSTRAINT PK_CAT PRIMARY KEY (ID_CAT)
);

INSERT INTO CATEGORIAS 
(ID_CAT, NM_CAT)
VALUES
(1,"Pizzas"),
(2,"Bebidas"),
(3,"Porções");


CREATE TABLE CLIENTES( 
	ID_CLIENTE INT NOT NULL 
	,NM_CLIENTE VARCHAR(255) NOT NULL 
	,TEL_CLIENTE VARCHAR(13) NOT NULL 
	,END_CLIENTE VARCHAR(255) NOT NULL 
	,NUM_CLIENTE VARCHAR(10) NOT NULL 
	,COM_CLIENTE VARCHAR(255) NULL DEFAULT NULL 
	,BAO_CLIENTE VARCHAR(255) NOT NULL 
	,CID_CLIENTE VARCHAR(255) NOT NULL 
	,CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE)
    ,CONSTRAINT UN_TELEFONE UNIQUE(TEL_CLIENTE)
);

INSERT INTO CLIENTES
(ID_CLIENTE, NM_CLIENTE, TEL_CLIENTE, END_CLIENTE, NUM_CLIENTE, COM_CLIENTE, BAO_CLIENTE, CID_CLIENTE)
VALUES
(1,"Julio Cocielo","13981231988","Rua 10","2","Casa","Jardim Castelo","São Vicente"),
(2,"Rogerio da Silva","13901828380","Rua 11","43","Casa","Jardim Gloria","Santos"),
(3,"Gabriel Rogerio","13998028938","Rua Agnaldo Figueira","5423","Casa","Porteira","Santos"),
(4,"Rose Oliveira","13989029384","Rua Marechal","234","Casa","Vila Ema","Praia Grande"),
(5,"Leonardo da Vinci","13997182039","Rua Tempo de Eli","223","Casa","Vila Volturua","São Vicente");



CREATE TABLE PRODUTOS(
	ID_PRODUTO INT NOT NULL
	,ID_CAT INT NOT NULL
	,NM_PRODUTO VARCHAR(255) NOT NULL
	,VAL_PRODUTO DECIMAL(10,2) NOT NULL
	,CONSTRAINT PK_PRODUTO PRIMARY KEY (ID_PRODUTO)
	,CONSTRAINT FK_CATEGORIA
		FOREIGN KEY (ID_CAT)
		REFERENCES CATEGORIAS(ID_CAT)
);

INSERT INTO PRODUTOS
(ID_PRODUTO, ID_CAT, NM_PRODUTO, VAL_PRODUTO)
VALUES
(1, 1,"Marguerita", 20.00),
(2, 2,"Guarana", 14.00),
(3, 3,"Batata", 12.00);

select * from PRODUTOS;

CREATE TABLE PEDIDOS(
	ID_PEDIDO INT NOT NULL
	,ID_CLIENTE INT NOT NULL
	,VAL_TOTAL DECIMAL(10,2)
	,CONSTRAINT PK_PEDIDO PRIMARY KEY (ID_PEDIDO)
	,CONSTRAINT FK_PEDIDO_CLIENTE
		FOREIGN KEY (ID_CLIENTE)
		REFERENCES CLIENTES(ID_CLIENTE)
);


INSERT INTO PEDIDOS
(ID_PEDIDO, ID_CLIENTE, VAL_TOTAL)
VALUES
(1, 1, 40.00);


CREATE TABLE PRODUTOSPEDIDO(
	ID_PEDIDO INT NOT NULL
	,ID_PRODUTO INT NOT NULL
	,QTD_PRODUTO INT NOT NULL
    ,VAL_PEDIDO DECIMAL(10,2) NOT NULL
	,CONSTRAINT PK_PRODUTO_PEDIDO PRIMARY KEY (ID_PEDIDO, ID_PRODUTO)
	,CONSTRAINT FK_PEDIDOS
		FOREIGN KEY (ID_PEDIDO)
		REFERENCES PEDIDOS(ID_PEDIDO)
	,CONSTRAINT FK_PRODUTO
		FOREIGN KEY (ID_PRODUTO)
		REFERENCES PRODUTOS(ID_PRODUTO)
);

INSERT INTO PRODUTOSPEDIDO
(ID_PEDIDO, ID_PRODUTO, QTD_PRODUTO, VAL_PEDIDO)
VALUES
(1,1,2, 40.00);

select * from produtospedido where id_pedido = 3;